BCCWebApp/Models/Deck.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BCCWebApp.Models
{
    public class Deck
    {
        public int Id { get; set; }
        [ForeignKey("User")]
        public string UserId { get; set; }
        public string Name { get; set; }
        [StringLength(4, MinimumLength = 1)]
        public string NaviName { get; set; }
        [StringLength(29, MinimumLength = 29)]
        public string NaviCode { get; set; }
        public int Wins { get; set; }
        public int Battles { get; set; }
    
        public Deck()
        {
        }
    }
}

BCCWebApp/Controllers/Api/DecksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BCCWebApp.Data;
using BCCWebApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace BCCWebApp.Controllers.Api
{
    [Authorize(AuthenticationSchemes = "Jwt")]
    [Route("api/[controller]")]
    [ApiController]
    public class DecksController : ControllerBase
    {
        private readonly BCCDbContext _context;
        private Random rnd;

        public DecksController(BCCDbContext context)
        {
            _context = context;
            rnd = new Random();
        }

        // GET: api/Decks
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Deck>>> GetDecks([FromQuery] int[] id, [FromQuery] bool random = false, [FromQuery] int count = -1)
        {
            List<Deck> decks = await _context.Decks.ToListAsync();

            if (id.Length > 0)
            {
                decks = decks.FindAll(d => id.Contains(d.Id));
            }

            if (random)
            {
                decks = decks.OrderBy(x => rnd.Next()).ToList();
            }

            if (count > 0)
            {
                return decks.Take(count).ToList();
            }
            else
            {
                return decks;
            }
        }
    }
}

BCCWebApp/Controllers/DecksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;
using BCCWebApp.Data;
using BCCWebApp.Models;
using BCCWebApp.Scripts;
using BCCWebApp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Host.Mef;

namespace BCCWebApp.Controllers
{
    public class DecksController : Controller
    {
        private readonly BCCDbContext context;

        public DecksController(BCCDbContext dbContext)
        {
            context = dbContext;
        }

        [Authorize]
        [Route("/decks")]
        public IActionResult Index()
        {
            ViewBag.Decks = context.Decks.Where(d => d.UserId == User.FindFirst(ClaimTypes.NameIdentifier).Value).ToList();
            ViewBag.SelectedDeckId = context.Users.Where(u => u.Id == User.FindFirst(ClaimTypes.NameIdentifier).Value).FirstOrDefault().CurrentDeckId;
            ViewBag.User = context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);

            return View();
        }

        [Authorize]
        [Route("/decks/add")]
        public IActionResult Add()
        {
            AddOrEditDeckViewModel addOrEditDeckViewModel = new AddOrEditDeckViewModel();

            return View(addOrEditDeckViewModel);
        }

        [Authorize]
        [Route("/decks/import")]
        public IActionResult Import()
        {
            ImportDeckViewModel importDeckViewModel = new ImportDeckViewModel();

            return View(importDeckViewModel);
        }

        [Authorize]
        [Route("/decks/edit/{id}")]
        public IActionResult Edit(int id)
        {
            Deck deck = context.Decks.Find(id);
            if (deck != null)
            {
                if (deck.UserId == User.FindFirst(ClaimTypes.NameIdentifier).Value)
                {
                    AddOrEditDeckViewModel addOrEditDeckViewModel = new AddOrEditDeckViewModel(deck);
                    return View(addOrEditDeckViewModel);
                } else
                {
                    return BadRequest();
                }
            }

            return NotFound();
        }

        [Authorize]
        [HttpGet("/decks/delete/{id}")]
        public IActionResult Delete(int id)
        {
            Deck deck = context.Decks.Find(id);
            if (deck != null)
            {
                if (deck.UserId == User.FindFirst(ClaimTypes.NameIdentifier).Value)
                {
                    context.Decks.Remove(deck);
                    context.SaveChanges();

                    return Redirect("/Decks");
                }
                else
                {
                    return BadRequest();
                }
            }
            return NotFound();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ProcessAddDeckForm(AddOrEditDeckViewModel addOrEditDeckViewModel)
        {
            if (ModelState.IsValid)
            {
                string naviCode = GenerateNaviCode(addOrEditDeckViewModel);
                Deck newDeck = new Deck
                {
                    UserId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value,
                    Name = addOrEditDeckViewModel.DeckName,
                    NaviName = MakeNaviName(User.Identity.Name),
                    NaviCode = naviCode,
                    Wins = 0,
                    Battles = 0
                };

                context.Decks.Add(newDeck);
                context.SaveChanges();

                return Redirect("/Decks");
            }

            return View("Add", addOrEditDeckViewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ProcessEditDeckForm(AddOrEditDeckViewModel addOrEditDeckViewModel)
        {
            if (ModelState.IsValid)
            {
                string naviCode = GenerateNaviCode(addOrEditDeckViewModel);

                Deck deck = context.Decks.Find(addOrEditDeckViewModel.DeckId);
                if (deck != null)
                {
                    if (deck.UserId == User.FindFirst(ClaimTypes.NameIdentifier).Value)
                    {
                        deck.Name = addOrEditDeckViewModel.DeckName;
                        deck.NaviCode = naviCode;
                        context.SaveChanges();

                        return Redirect("/Decks");
                    } else
                    {
                        return BadRequest();
                    }
                } else
                {
                    return NotFound();
                }
            }

            return View("Edit", addOrEditDeckViewModel);
        }

        [Authorize]
        [HttpPut("/decks/SetChosenDeck")]
        public IActionResult SetChosenDeck(int chosenId)
        {
            Deck chosenDeck = context.Decks.Find(chosenId);
            if (chosenDeck != null)
            {
                string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                if (chosenDeck.UserId == userId)
                {
                    User appUser = context.Users.Find(userId);
                    appUser.CurrentDeckId = chosenId;
                    context.SaveChanges();

                    return Json("Ok");
                }
            }
            return Json("Bad Request");
        }

        private string MakeNaviName(string name)
        {
            string naviName = name.ToUpper();
            if (naviName.Length > 4)
            {
                string vowelless = new string(naviName.Where(c => !"AEIOUY".Contains(c)).ToArray());
                if (vowelless.Length > 1)
                {
                    naviName = vowelless;
                }
            }
            if (naviName.Length > 4)
            {
                naviName = naviName.Substring(0, 4);
            }

            return naviName;
        }

        private string GenerateNaviCode(AddOrEditDeckViewModel addOrEditDeckViewModel)
        {
            string naviName = MakeNaviName(User.Identity.Name);

            int[] data = new int[]
            {
                addOrEditDeckViewModel.Operator,
                addOrEditDeckViewModel.ChipNavi,
                addOrEditDeckViewModel.Chip1a,
                addOrEditDeckViewModel.Chip1b,
                addOrEditDeckViewModel.Chip2a,
                addOrEditDeckViewModel.Chip2b,
                addOrEditDeckViewModel.Chip2c,
                addOrEditDeckViewModel.Chip3a,
                addOrEditDeckViewModel.Chip3b,
                addOrEditDeckViewModel.Chip3c,
                addOrEditDeckViewModel.Chip3d,
                addOrEditDeckViewModel.ChipR,
                addOrEditDeckViewModel.ChipL,
                BCCData.CodeTypes["Game Boy Advance"],  // Code type here doesn't matter, just default to GBA
                0,                                      // Checksum (will be calculated later)
            };

            string naviCode = Util.PackNaviCode(naviName, data);
            naviCode = Util.Decorate(naviCode);

            return naviCode;
        }
    }
}

BCCWebApp/Views/Decks/Add.cshtml
@model BCCWebApp.ViewModel.AddDeckViewModel;

@*Deck form code modified and based on https://therockmanexezone.com/ncgen/ by Prof9 (https://github.com/Prof9)*@
<link rel="stylesheet" href="~/css/ncgen/style.css">
<script src="~/js/ncgen/data.js"></script>
<script type="text/javascript">
    function getChipMB(name) {
        var chip = parseInt(document.getElementsByName(name)[0].value);
        if (chip <= 0) {
            return 0;
        }
        var mb = NCData.mb[chip];
        return mb;
    }

    function updateChipIcon(name) {
        var chip = parseInt(document.getElementsByName(name)[0].value);
        if (chip < 0 || (chip > 190 && chip < 200) || chip > 248) {
            chip = 0;
        }
        var img = document.getElementsByClassName(name.replace('Chip', 'ChipIcon'))[0];
        img.src = "../images/ncgen/icon/" + chip + ".png";
    }


    function updateDeck() {
        var maxMB = getChipMB('ChipNavi');

        var curMB = 0;
        curMB += getChipMB('Chip1a');
        curMB += getChipMB('Chip1b');
        curMB += getChipMB('Chip2a');
        curMB += getChipMB('Chip2b');
        curMB += getChipMB('Chip2c');
        curMB += getChipMB('Chip3a');
        curMB += getChipMB('Chip3b');
        curMB += getChipMB('Chip3c');
        curMB += getChipMB('Chip3d');

        var operator = parseInt(document.getElementsByName("Operator")[0].value);
        document.getElementsByClassName('slotin')[0].innerHTML = NCData.slotIn[operator];

        document.getElementsByClassName('mb-current')[0].innerHTML = curMB;
        document.getElementsByClassName('mb-max')[0].innerHTML = maxMB;

        var mbElem = document.getElementsByClassName('mb')[0];
        if (curMB > maxMB) {
            mbElem.style.fontWeight = 'bold';
            mbElem.style.color = 'red';
            document.getElementById('submit-button').disabled = true;
        } else {
            mbElem.style.fontWeight = '';
            mbElem.style.color = '';
            document.getElementById('submit-button').disabled = false;
        }

        updateChipIcon('ChipR');
        updateChipIcon('ChipNavi');
        updateChipIcon('ChipL');
        updateChipIcon('Chip1a');
        updateChipIcon('Chip1b');
        updateChipIcon('Chip2a');
        updateChipIcon('Chip2b');
        updateChipIcon('Chip2c');
        updateChipIcon('Chip3a');
        updateChipIcon('Chip3b');
        updateChipIcon('Chip3c');
        updateChipIcon('Chip3d');
    }
</script>

<form asp-controller="Decks" asp-action="ProcessAddDeckForm" method="post">
    <table style="width: 520px; border-collapse: collapse; border-spacing: 0; text-align: left; margin: auto;">
        <tr>
            <td style="width: 1px; white-space: nowrap;">
                <label asp-for="DeckName">Deck Name:</label>
            </td>
            <td colspan="9999">
                <input style="width: 100%" asp-for="DeckName" />
            </td>
        </tr>
        <tr>
            <td style="width: 1px; white-space: nowrap;">
                <label asp-for="Operator">Operator:</label>
            </td>
            <td colspan="9999">
                <select class="operator" asp-for="Operator" asp-items="Model.Operators" onchange="updateDeck();"></select>
                <span style="color: grey; font-size: smaller">(Slots in at <span class="slotin">--</span>%)</span>
            </td>
        </tr>
        <tr>
            <td colspan="4"></td>
            <td class="mb" style="text-align: right;">
                <span>MB: </span>
                <span class="mb-current">0</span><span>/</span><span class="mb-max">0</span>
            </td>
        </tr>
        <tr>
            <td colspan="5">
                <table class="deck">
                    <tr>
                        <td class="deck-c1">
                            <div class="box-lr box-r">
                                <label class="label-lr" asp-for="ChipR">R</label>
                                <div class="chip-box">
                                    <img width="16" height="16" class="chip-icon ChipIconR" src="~/images/ncgen/icon/0.png">
                                    <select class="chip" asp-for="ChipR" asp-items="Model.Chips" onchange="updateDeck();"></select>
                                </div>
                            </div>
                            <div>
                                <label class="label-lr" asp-for="ChipNavi">Navi</label>
                                <div class="chip-box chip-box-navi">
                                    <img width="16" height="16" class="chip-icon ChipIconNavi" src="~/images/ncgen/icon/200.png">
                                    <select class="chip-navi" asp-for="ChipNavi" asp-items="Model.NaviChips" onchange="updateDeck();"></select>
                                </div>
                            </div>
                            <div class="box-lr box-l">
                                <label class="label-lr" asp-for="ChipL">L</label>
                                <div class="chip-box">
                                    <img width="16" height="16" class="chip-icon ChipIconL" src="~/images/ncgen/icon/0.png">
                                    <select class="chip" asp-for="ChipL" asp-items="Model.Chips" onchange="updateDeck();"></select>
                                </div>
                            </div>
                        <td><img src="~/images/ncgen/pipe1.png" width="8" height="13"></td>
                        <td class="deck-c2">
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon1a" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip1a" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon1b" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip1b" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                        </td>
                        <td><img src="~/images/ncgen/pipe2.png" width="8" height="30"></td>
                        <td class="deck-c3">
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon2a" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip2a" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon2b" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip2b" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon2c" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip2c" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                        </td>
                        <td><img src="~/images/ncgen/pipe3.png" width="8" height="47"></td>
                        <td class="deck-c4">
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon3a" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip3a" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon3b" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip3b" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon3c" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip3c" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon3d" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip3d" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                        </td>
                    </tr>
                </table>
                <input id="submit-button" type="submit" value="Submit" />
            </td>
        </tr>
    </table>
</form>
<script type="text/javascript">updateDeck();</script>

BCCWebApp/Views/Decks/Edit.cshtml
@model BCCWebApp.ViewModel.AddOrEditDeckViewModel;

@*Deck form code modified and based on https://therockmanexezone.com/ncgen/ by Prof9 (https://github.com/Prof9)*@
<link rel="stylesheet" href="~/css/ncgen/style.css">
<script src="~/js/ncgen/data.js"></script>
<script type="text/javascript">
    function getChipMB(name) {
        var chip = parseInt(document.getElementsByName(name)[0].value);
        if (chip <= 0) {
            return 0;
        }
        var mb = NCData.mb[chip];
        return mb;
    }

    function updateChipIcon(name) {
        var chip = parseInt(document.getElementsByName(name)[0].value);
        if (chip < 0 || (chip > 190 && chip < 200) || chip > 248) {
            chip = 0;
        }
        var img = document.getElementsByClassName(name.replace('Chip', 'ChipIcon'))[0];
        img.src = "../../images/ncgen/icon/" + chip + ".png";
    }


    function updateDeck() {
        var maxMB = getChipMB('ChipNavi');

        var curMB = 0;
        curMB += getChipMB('Chip1a');
        curMB += getChipMB('Chip1b');
        curMB += getChipMB('Chip2a');
        curMB += getChipMB('Chip2b');
        curMB += getChipMB('Chip2c');
        curMB += getChipMB('Chip3a');
        curMB += getChipMB('Chip3b');
        curMB += getChipMB('Chip3c');
        curMB += getChipMB('Chip3d');

        var operator = parseInt(document.getElementsByName("Operator")[0].value);
        document.getElementsByClassName('slotin')[0].innerHTML = NCData.slotIn[operator];

        document.getElementsByClassName('mb-current')[0].innerHTML = curMB;
        document.getElementsByClassName('mb-max')[0].innerHTML = maxMB;

        var mbElem = document.getElementsByClassName('mb')[0];
        if (curMB > maxMB) {
            mbElem.style.fontWeight = 'bold';
            mbElem.style.color = 'red';
            document.getElementById('submit-button').disabled = true;
        } else {
            mbElem.style.fontWeight = '';
            mbElem.style.color = '';
            document.getElementById('submit-button').disabled = false;
        }

        updateChipIcon('ChipR');
        updateChipIcon('ChipNavi');
        updateChipIcon('ChipL');
        updateChipIcon('Chip1a');
        updateChipIcon('Chip1b');
        updateChipIcon('Chip2a');
        updateChipIcon('Chip2b');
        updateChipIcon('Chip2c');
        updateChipIcon('Chip3a');
        updateChipIcon('Chip3b');
        updateChipIcon('Chip3c');
        updateChipIcon('Chip3d');
    }
</script>

<form asp-controller="Decks" asp-action="ProcessEditDeckForm" method="post">
    <input asp-for="DeckId" value="@Model.DeckId" hidden />
    <table style="width: 520px; border-collapse: collapse; border-spacing: 0; text-align: left; margin: auto;">
        <tr>
            <td style="width: 1px; white-space: nowrap;">
                <label asp-for="DeckName">Deck Name:</label>
            </td>
            <td colspan="9999">
                <input style="width: 100%" asp-for="DeckName" />
            </td>
        </tr>
        <tr>
            <td style="width: 1px; white-space: nowrap;">
                <label asp-for="Operator">Operator:</label>
            </td>
            <td colspan="9999">
                <select class="operator" asp-for="Operator" asp-items="Model.Operators" onchange="updateDeck();"></select>
                <span style="color: grey; font-size: smaller">(Slots in at <span class="slotin">--</span>%)</span>
            </td>
        </tr>
        <tr>
            <td colspan="4"></td>
            <td class="mb" style="text-align: right;">
                <span>MB: </span>
                <span class="mb-current">0</span><span>/</span><span class="mb-max">0</span>
            </td>
        </tr>
        <tr>
            <td colspan="5">
                <table class="deck">
                    <tr>
                        <td class="deck-c1">
                            <div class="box-lr box-r">
                                <label class="label-lr" asp-for="ChipR">R</label>
                                <div class="chip-box">
                                    <img width="16" height="16" class="chip-icon ChipIconR" src="~/images/ncgen/icon/0.png">
                                    <select class="chip" asp-for="ChipR" asp-items="Model.Chips" onchange="updateDeck();" value="@Model.ChipR"></select>
                                </div>
                            </div>
                            <div>
                                <label class="label-lr" asp-for="ChipNavi">Navi</label>
                                <div class="chip-box chip-box-navi">
                                    <img width="16" height="16" class="chip-icon ChipIconNavi" src="~/images/ncgen/icon/200.png">
                                    <select class="chip-navi" asp-for="ChipNavi" asp-items="Model.NaviChips" onchange="updateDeck();" value="@Model.ChipNavi"></select>
                                </div>
                            </div>
                            <div class="box-lr box-l">
                                <label class="label-lr" asp-for="ChipL">L</label>
                                <div class="chip-box">
                                    <img width="16" height="16" class="chip-icon ChipIconL" src="~/images/ncgen/icon/0.png">
                                    <select class="chip" asp-for="ChipL" asp-items="Model.Chips" onchange="updateDeck();" value="@Model.ChipL"></select>
                                </div>
                            </div>
                        <td><img src="~/images/ncgen/pipe1.png" width="8" height="13"></td>
                        <td class="deck-c2">
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon1a" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip1a" asp-items="Model.Chips" onchange="updateDeck();" value="@Model.Chip1a"></select>
                            </div>
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon1b" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip1b" asp-items="Model.Chips" onchange="updateDeck();" value="@Model.Chip1b"></select>
                            </div>
                        </td>
                        <td><img src="~/images/ncgen/pipe2.png" width="8" height="30"></td>
                        <td class="deck-c3">
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon2a" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip2a" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon2b" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip2b" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon2c" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip2c" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                        </td>
                        <td><img src="~/images/ncgen/pipe3.png" width="8" height="47"></td>
                        <td class="deck-c4">
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon3a" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip3a" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon3b" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip3b" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon3c" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip3c" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                            <div class="chip-box">
                                <img width="16" height="16" class="chip-icon ChipIcon3d" src="~/images/ncgen/icon/0.png">
                                <select class="chip" asp-for="Chip3d" asp-items="Model.Chips" onchange="updateDeck();"></select>
                            </div>
                        </td>
                    </tr>
                </table>
                <input id="submit-button" type="submit" value="Submit" />
            </td>
        </tr>
    </table>
</form>
<script type="text/javascript">updateDeck();</script>

BCCWebApp/Views/Decks/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<script type="text/javascript">
    function SetChosenDeck() {
        var chosenId = document.querySelector('input[name="chosen-deck"]:checked').value;
        $.ajax({
            url: '/Decks/SetChosenDeck',
            type: 'PUT',
            data: { chosenId: chosenId, }
        });
    }
</script>
<h1 class="display-4">Your Decks</h1>

<table class="table">
    <tr>
        <th></th>
        <th>Name</th>
        <th>Deck</th>
        <th>Wins / Battles</th>
        <th></th>
        <th></th>
    </tr>
    @if (ViewBag.Decks.Count != 0)
    {
        <link rel="stylesheet" href="~/css/ncgen/style.css">

        @foreach (Deck deck in ViewBag.Decks)
        {
            string winrate = "";
            @if (deck.Battles == 0)
            {
                winrate = "No Battles Yet!";
            }
            else
            {
                winrate = (deck.Wins / (double)deck.Battles).ToString("P2");
            }
            <tr>
                <td>
                    @if (deck.Id == ViewBag.SelectedDeckId)
                    {
                        <input type="radio" name="chosen-deck" onclick="SetChosenDeck();" value="@deck.Id" checked="checked" />
                    }
                    else
                    {
                        <input type="radio" name="chosen-deck" onclick="SetChosenDeck();" value="@deck.Id" />
                    }
                </td>
                <td>@deck.Name</td>
                <td>
                    <partial name="_DeckViewer" model="new BCCWebApp.ViewModel.DeckViewerViewModel(deck.NaviName, deck.NaviCode)" />
                </td>
                <td>
                    <a href="#" data-toggle="tooltip" title="@winrate Win Rate">@deck.Wins / @deck.Battles</a>
                </td>
                <td><a class="btn btn-sm btn-primary" href="~/decks/edit/@deck.Id">Edit</a></td>
                <td><a class="btn btn-sm btn-danger" href="~/decks/delete/@deck.Id">Delete</a></td>
            </tr>
        }
    }
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td>
            @{
                string totalWinRate = "";
                @if (ViewBag.User.TotalBattles == 0)
                {
                    totalWinRate = "No Battles Yet!";
                }
                else
                {
                    totalWinRate = (ViewBag.User.TotalWins / (double)ViewBag.User.TotalBattles).ToString("P2");
                }
            }
            <a href="#" data-toggle="tooltip" title="@totalWinRate Total Win Rate">@ViewBag.User.TotalWins / @ViewBag.User.TotalBattles</a>
        </td>
        <td></td>
        <td></td>
    </tr>
</table>
<a class="btn btn-sm btn-primary" asp-controller="Decks" asp-action="Add">New Deck</a>
@*<a class="btn btn-sm btn-secondary" asp-controller="Decks" asp-action="Import">Import Deck</a>*@

<script type="text/javascript">
    
</script>